#!/bin/sh /etc/rc.common
#    Copyright (C) 2017 Gui Iribarren <gui@altermundi.net>
#
#    This is free software, licensed under the GNU General Public License v3.

START=91
USE_PROCD=1

start_service() {
    procd_open_instance "wget_esp_curl_loop"
    procd_set_param command "/root/wget_esp_curl_loop.sh"

    ### Respawn automatically when process dies, after waiting respawn_timeout seconds
    ### If respawn_retry consecutives respawns die before respawn_threshold seconds (i.e. they crash)
    ### it will stop trying and leave it dead.
    procd_set_param respawn ${respawn_threshold:-60} ${respawn_timeout:-5} ${respawn_retry:-60}

    procd_close_instance
}

